### ISSUE TITLE
[Issue] Server crashing when Tile Entities break blocks

### ISSUE THREAD

**Issue by Quarris** [alfuken/chunk_claim#1]
Minecraft Version: 1.12.2
Mod Version: 4
Forge Version: forge-14.23.5.2831
Crash Log: [https://pastebin.com/uifkm2E7](crash-log)
This crash occurred on a SF4 server.
Plant Sower from Industrial Foregoing crashes server when attempting to plant seed in a claimed area.
From the crash log the problem seems to be with FakePlayer s, but I cannot see exactly where the NPE is coming from.
To help the 2 functions in question for the EntityPlayerMP are sendAllContents() and sendContainerToPlayer() (if you have same mappings as me).

**Comment by alfuken** [comment]
Well, that raised a good question: should machines be allowed to perform environmental actions in protected areas?

If they are disallowed, it limits the automation possibilities for players. And it is not always possible to check who have placed the machine in question.
If they are allowed, anyone can place, for example, lava dispenser at the border of claimed chunk and flood your chunk with lava.

I tend to go with second option though... What would be your thoughts?

**Comment by Quarris** [comment]
So I am always for letting things be configurable if need be. The way I would go about it is that the player should have control if they want to allow fake players to interact with their claim or not.

**Comment by alfuken** [comment]
yeah, but what's the default value you'd be expecting?

**Comment by Quarris** [comment]
The default should be disallow fake players

**Comment by alfuken** [comment]
👍 

Will implement somewhere this week.

**Comment by Quarris** [comment]
Just to make sure, the same thing may happen when fake players place stuff as well

**Comment by 12autogroup** [comment]
Sorry, man, completely forgot about your request and update got a bit delayed, but here it is!

**Comment by alfuken** [comment]
Sorry, man, completely forgot about your request and update got a bit delayed, but here it is!
