### ISSUE TITLE
[1.14.4] disable_explosions = true disables explosions in unclaimed chunks

### ISSUE THREAD

**Issue by Partonetrain** [alfuken/chunk_claim#5]
The opposite was true in 2.7.0 - the option did nothing

**Comment by Szum123321** [comment]
It seems like the last commit haven't reapired issue fully besause after changing List<BlockPos> list = explosion.getAffectedBlockPositions(); back to List<BlockPos> list = new ArrayList<>(explosion.getAffectedBlockPositions()); in EventHandlers.java explosions seem to work properly.
